### ISSUE TITLE
AsyncPacketReader线程读取数据貌似不稳定？

### ISSUE THREAD

**Issue by zlp1992** [mpusher/mpush-client-java#2]
使用mpush-client-java与mpush-android在模拟器上测试时，模拟器端的AsyncPacketReader里的connection貌似不稳定？在读取数据的时候时不时会跑出异常，然后重连。
异常信息为：
`D/MPUSH: >>> receive heartbeat pong...
I/Choreographer: Skipped 563 frames!  The application may be doing too much work on its main thread.
D/dalvikvm: GC_FOR_ALLOC freed 533K, 15% free 3571K/4172K, paused 197ms, total 199ms
I/Choreographer: Skipped 267 frames!  The application may be doing too much work on its main thread.
I/Choreographer: Skipped 49 frames!  The application may be doing too much work on its main thread.
W/MPUSH: heartbeat timeout times=2
W/MPUSH: heartbeat timeout times=2 over limit=2, client restart
W/System.err: java.nio.channels.ClosedByInterruptException
W/MPUSH: connection closed !!!
W/System.err:     at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:113)
W/System.err:     at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:333)
W/System.err:     at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:289)
W/System.err:     at com.mpush.codec.AsyncPacketReader.read(AsyncPacketReader.java:100)
W/System.err:     at com.mpush.codec.AsyncPacketReader.run(AsyncPacketReader.java:77)
W/System.err:     at java.lang.Thread.run(Thread.java:841)
E/MPUSH: read packet ex, do reconnect
         java.nio.channels.ClosedByInterruptException
             at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:113)
             at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:333)
             at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:289)
             at com.mpush.codec.AsyncPacketReader.read(AsyncPacketReader.java:100)
             at com.mpush.codec.AsyncPacketReader.run(AsyncPacketReader.java:77)
             at java.lang.Thread.run(Thread.java:841)
W/MPUSH: read an error, do reconnect!!!
D/MPUSH: try doReconnect, count=1, total=2, autoConnect=true, state=connecting
W/MPUSH: doReconnect, count=1, total=2, autoConnect=true, state=connecting
W/MPUSH: try connect server [115.156.162.79:3000`

**Comment by ghost** [comment]
我也遇到了这个问题， 请问你是如何解决的？

**Comment by lmmarisej** [comment]
同
